### ISSUE TITLE
Support for Polylang

### ISSUE THREAD

**Issue by maevelander** [maevelander/sticky-side-buttons#10]
Logging a request for Polylang support: 
https://wordpress.org/support/topic/support-for-polylang-needed/

Relates to https://github.com/maevelander/sticky-side-buttons/issues/4

**Comment by imomer** [comment]
Maeve! can you be more specific about the client's request... Is he referring to support of [polylang plugin](https://wordpress.org/plugins/polylang/) if yes, how?

Because our plugin is ready for translation ... so not sure what he is asking for?

**Comment by maevelander** [comment]
He means that polylang plugin is not picking up the button text entered by the end user and making it translatable through polylang. The same thing the wpml issue mentioned. Polylang docs say it's compatible with wpml api so if we make this compatible for wpml the way the plugin author suggested, it will also resolve this for polylang

**Comment by imomer** [comment]
It is compatible with wpml ... did you check?
