### ISSUE TITLE
Checkboxes do not support custom post types

### ISSUE THREAD

**Issue by maevelander** [maevelander/sticky-side-buttons#14]
@imomer The new checkboxes added in v1.0.4 show pages, posts, front page... but do not show custom post types.  Can we add support for custom post types please?

**Comment by imomer** [comment]
Custom post types that site already has?

**Comment by maevelander** [comment]
Correct

**Comment by imomer** [comment]
Well never think of that before :p 

I thought we discuss only posts, pages and home page

**Comment by maevelander** [comment]
https://codex.wordpress.org/Function_Reference/get_post_types should help

**Comment by imomer** [comment]
Actually currently this part is coded with a different logic. I think I might have to recode this...

**Comment by Base29** [comment]
support for CPTs added

**Comment by maevelander** [comment]
Fixed by https://github.com/maevelander/sticky-side-buttons/pull/17
