### ISSUE TITLE
Open in new tab option

### ISSUE THREAD

**Issue by maevelander** [maevelander/sticky-side-buttons#2]
By user request: Add an option to open button links in new tab with target=”_blank” so user can choose which one’s should open in a new tab.

**Comment by imomer** [comment]
Now user can choose which button will open its link in a new window... PR on its way

**Comment by maevelander** [comment]
Wonderful, thanks Omer!

**Comment by maevelander** [comment]
Added in https://github.com/maevelander/sticky-side-buttons/pull/11
