### ISSUE TITLE
Mobile: Slide on Hover

### ISSUE THREAD

**Issue by maevelander** [maevelander/sticky-side-buttons#3]
Behavior of slide on hover needs to be considered/improved for mobile.

**Comment by imomer** [comment]
Can you be more specific about this? 

Are we talking about detect a finger hovering on screen?

**Comment by maevelander** [comment]
Good question. How about... on mobile, buttons are always IN, then one touch expands them, second touch triggers the link action?

**Comment by imomer** [comment]
Well thats a bit tricky but not impossible :)

**Comment by imomer** [comment]
Done ... 👍

**Comment by maevelander** [comment]
Works perfectly, thanks so much @imomer 
Feature added in https://github.com/maevelander/sticky-side-buttons/pull/11
