### ISSUE TITLE
Buttons not translated with WPML

### ISSUE THREAD

**Issue by dgwatkins** [maevelander/sticky-side-buttons#4]
This is David from the WPML compatibility team. We received a support request about translating the button with WPML over here:
https://wpml.org/forums/topic/how-to-translate-customdynamic-string-in-stickybuttons-plugin/

The solution has 2 parts:

1) Adding a language configuration file to tell WPML what should be translated. This file goes in the root folder of your plugin:

```
<wpml-config>
    <admin-texts>
        <key name="ssb_buttons">
                    <key name="btns">
                        <key name="*">
                            <key name="btn_text" />
                            <key name="btn_link" />
                        </key>
                    </key>
        </key>
    </admin-texts>
</wpml-config>
```

You have more information about language configuration files over here:
https://wpml.org/documentation/support/language-configuration-files/

2) This plugin is loading options to early, before all plugins are loaded, thus WPML can not translate them. We suggested a workaround of adding get_option again to fix the issue. 

Added below code in ssb-ui.php line 339

`$this->buttons  = get_option( 'ssb_buttons' );`

You might know a better way of doing this so we dont need to call get_option twice.

The solution was confirmed here:
https://wpml.org/forums/topic/how-to-translate-customdynamic-string-in-stickybuttons-plugin/page/2/#post-1315804

**Comment by imomer** [comment]
Button text string wasn't marked for translation before, so I think this might be the cause for it not being translated before. Fixed it in PR!

**Comment by maevelander** [comment]
Nice work, thanks

**Comment by maevelander** [comment]
@dgwatkins Would it be possible for you to test latest version of this plugin please to confirm WPML compatibility?   We don't have a copy of WPML plugin as it's premium. Thanks for your help

**Comment by dgwatkins** [comment]
If you are the author of the plugin, you can signup here and get a developer license:
https://wpml.org/documentation/theme-compatibility/go-global-program/
From there we can coordinate testing to keep compatibility always up to date.
