### ISSUE TITLE
Add feature to show only on front page

### ISSUE THREAD

**Issue by maevelander** [maevelander/sticky-side-buttons#5]
It would be really nice to add a checkbox so user can show buttons only on frontpage.

**Comment by EnigmaWeb** [comment]
I've seen it done in quite a few other plugins with checkbox options like.

Show on:
Pages
Posts
Frontpage Only

**Comment by imomer** [comment]
Feature added.... Will initiate PR

**Comment by maevelander** [comment]
Nice!

**Comment by maevelander** [comment]
Featured added in https://github.com/maevelander/sticky-side-buttons/pull/11
