### ISSUE TITLE
Buttons not visible in Safari

### ISSUE THREAD

**Issue by maevelander** [maevelander/sticky-side-buttons#6]
https://wordpress.org/support/topic/safari-not-visible/#post-9516471

**Comment by imomer** [comment]
Buttons are working fine in safari ... I have tested the reporting user's own site in my safari.
![sticky-buttons-sfari](https://user-images.githubusercontent.com/773535/36368036-4463b658-1577-11e8-9f28-06532130e214.gif)

**Comment by maevelander** [comment]
Thanks for testing. Closing this issue
