### ISSUE TITLE
i to span

### ISSUE THREAD

**Issue by maevelander** [maevelander/sticky-side-buttons#8]
From https://wordpress.org/support/topic/i-to-span/

Could you change the i to span for fa-icon so it can pass accessibility check? For example <i class=”fa fa-address-card-o” aria-hidden=”true”></i> to <span class=”fa fa-address-card-o” aria-hidden=”true”></span>

**Comment by imomer** [comment]
Fixed... Will create a PR

**Comment by maevelander** [comment]
Fixed by https://github.com/maevelander/sticky-side-buttons/pull/11
