### ISSUE TITLE
controlling colors

### ISSUE THREAD

**Issue by Judy101101** [maevelander/sticky-side-buttons#9]
I can't seem to get a background color, it's taking on the same style as my main menu so even the font color is affected but I'm mainly concerned with background so I can see the button

**Comment by maevelander** [comment]
Hi Judy, this isn't a bug in the plugin, it's something specific to your site. Therefore, I'm going to close this as an issue here on GitHub, and if you could please re-submit this over on the support forum I'd be happy to help you troubleshoot there. Thanks.

https://wordpress.org/support/plugin/sticky-side-buttons
